### ISSUE TITLE
unable to access code

### ISSUE THREAD

**Issue by tvchamundeswaridevi** [soumya997/Music-Generation-Using-Deep-Learning#1]
unable to view the code of "Music Generation using ABC Sheet Music🎹.ipynb"

**Comment by soumya997** [comment]
Yeah, that is a large file `6.06 MB`, I think you are seeing `Sorry, something went wrong. Reload?`. This is because of file size. 
Solution:
1. you can clone the NB and view that locally.
2. you can use https://nbviewer.org/ to view the NB online.

Let me know @tvchamundeswaridevi, if the problem get resolved.

**Comment by tvchamundeswaridevi** [comment]
It worked out!
Thank you
